# Generated by Django 6.0.1 on 2026-06-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit — Fund Replenishment'), ('debit', 'Debit — Expense')], max_length=10)),
                ('category', models.CharField(choices=[('fund', 'Fund Replenishment'), ('office', 'Office Supplies'), ('logistics', 'Logistics & Courier'), ('hospitality', 'Hospitality'), ('travel', 'Travel & Transport'), ('maintenance', 'Maintenance'), ('utilities', 'Utilities'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Running balance after this entry (auto-set on save)', max_digits=12)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='petty_cash_receipts/%Y/%m/')),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Petty Cash Entry',
                'verbose_name_plural': 'Petty Cash Entries',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Petty Cash Fund',
                'verbose_name_plural': 'Petty Cash Fund',
            },
        ),
    ]
