# Generated by Django 6.0.1 on 2026-06-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('renew', 'Renew'), ('allocate', 'Allocate'), ('adjust', 'Adjust'), ('approve', 'Approve'), ('transfer', 'Transfer'), ('return', 'Return'), ('reschedule', 'Reschedule'), ('cancel', 'Cancel'), ('upload', 'Upload')], max_length=20)),
                ('resource', models.CharField(max_length=255)),
                ('resource_type', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
