# Generated by Django 6.0.1 on 2026-06-10 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='preferred_vendor',
            field=models.ForeignKey(blank=True, help_text='Default vendor auto-filled on new purchase orders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_items', to='masters.vendor'),
        ),
    ]
