"""
Django settings for inventory_backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path
import environ
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DESKTOP_RUNTIME_DIR = Path(
    os.environ.get("DESKTOP_RUNTIME_DIR", str(BASE_DIR))
).resolve()

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = DESKTOP_RUNTIME_DIR / "staticfiles"

env = environ.Env()

READ_DOT_ENV_FILE = env.bool("DJANGO_READ_DOT_ENV_FILE", default=False)
if READ_DOT_ENV_FILE:
    # OS environment variables take precedence over variables from .env
    env.read_env(str(BASE_DIR / ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-juhj$t%b^#kp9s5qxtv-3tnolo5zfed!z$tcq(dvnbe867vyr6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "0.0.0.0", "127.0.0.1"]  # noqa: S104

AUTH_USER_MODEL = 'users.User'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'inventory_backend.logging_config',
    'users',
    'masters',
    'purchases',
    'stock',
    'audit',
    'dashboard',
    'reports',
    'sales',
    'pettycash',
]

MIDDLEWARE = [
    'inventory_backend.logging_config.middleware.APILoggingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'inventory_backend.urls'
CORS_ALLOW_ALL_ORIGINS = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventory_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("POSTGRES_DB", default="urban_inventory_db"),
        "USER": os.environ.get("PG_USER") or env("POSTGRES_USER", default="postgres"),
        "PASSWORD": env("POSTGRES_PASSWORD", default="password"),
        "HOST": env("POSTGRES_HOST", default="127.0.0.1"),
        "PORT": os.environ.get("PG_PORT") or env("POSTGRES_PORT", default="5432"),
    }
}



import ssl
import certifi

os.environ.setdefault("SSL_CERT_FILE", certifi.where())
os.environ.setdefault("REQUESTS_CA_BUNDLE", certifi.where())

EMAIL_SSL_CONTEXT = ssl.create_default_context(
    cafile=certifi.where()
)
EMAIL_BACKEND = 'inventory_backend.mail_backend.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

EMAIL_HOST_USER = 'elangoroman890@gmail.com'
EMAIL_HOST_PASSWORD = 'fzwvrchaxvlirosx'  # App Password ONLY

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_ALLOW_INSECURE_FALLBACK = DEBUG
# WhiteNoise

# https://docs.djangoproject.com/en/dev/ref/settings/#email-timeout
EMAIL_TIMEOUT = 5

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(DESKTOP_RUNTIME_DIR, 'media')

# Make sure MEDIA_ROOT directory exists
os.makedirs(MEDIA_ROOT, exist_ok=True)

# STATIC
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#static-root

# https://docs.djangoproject.com/en/dev/ref/settings/#static-url
STATIC_URL = "/static/"
# https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#std:setting-STATICFILES_DIRS

# https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#staticfiles-finders
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",    # unauthenticated requests
        "user": "1000/hour",   # authenticated requests
    },
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "EXCEPTION_HANDLER": "rest_framework.views.exception_handler",
}

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
     "OPTIONS": {"min_length": 8}},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME":  timedelta(hours=8),    # 8 hours for desktop app
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS":  True,                  # new refresh on every use
    "BLACKLIST_AFTER_ROTATION": True,                # old refresh is invalidated
    "AUTH_HEADER_TYPES":      ("Bearer",),
    "UPDATE_LAST_LOGIN":      True,
}


LANGUAGE_CODE = 'en-us'
TIME_ZONE     = 'UTC'
USE_I18N      = True
USE_TZ        = True
STATIC_URL    = 'static/'



# ─────────────────────────────────────────
#  LOGGING  — writes django.log next to .exe
# ─────────────────────────────────────────
LOGS_DIR = DESKTOP_RUNTIME_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)
 
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
 
    # ── Formatters ─────────────────────────────────────────────────────────────
    "formatters": {
 
        # Matches your required format exactly:
        # 2026-03-18 11:02:10 INFO  12345 users.views : Received request to fetch user ...
        "production": {
            "format":  "%(asctime)s %(levelname)-5s %(process)d %(name)s : %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
 
        # Extended format for error.log — adds thread name for debugging
        "verbose": {
            "format":  "%(asctime)s %(levelname)-5s %(process)d --- [%(threadName)s] %(name)s : %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
 
        # Short format for console (dev only)
        "simple": {
            "format": "%(levelname)-5s %(name)s : %(message)s",
        },
    },
 
    # ── Filters ────────────────────────────────────────────────────────────────
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
    },
 
    # ── Handlers ───────────────────────────────────────────────────────────────
    "handlers": {
 
        # Console — only active when DEBUG=True (development)
        "console": {
            "class":     "logging.StreamHandler",
            "formatter": "simple",
            "filters":   ["require_debug_true"],
            "level":     "DEBUG",
        },
 
        # app.log — all INFO+ logs from every app
        # (requests, responses, accounting, users, sales, purchase, etc.)
        # Rotates at 5 MB, keeps 10 files = 55 MB max
        "app_file": {
            "class":       "logging.handlers.RotatingFileHandler",
            "filename":    str(LOGS_DIR / "app.log"),
            "maxBytes":    5 * 1024 * 1024,
            "backupCount": 10,
            "formatter":   "production",
            "level":       "INFO",
            "encoding":    "utf-8",
        },
 
        # error.log — ERROR and CRITICAL only, with thread info + full traceback
        "error_file": {
            "class":       "logging.handlers.RotatingFileHandler",
            "filename":    str(LOGS_DIR / "error.log"),
            "maxBytes":    5 * 1024 * 1024,
            "backupCount": 10,
            "formatter":   "verbose",
            "level":       "ERROR",
            "encoding":    "utf-8",
        },
 
        # db.log — all DB create / update / delete events across all models
        "db_file": {
            "class":       "logging.handlers.RotatingFileHandler",
            "filename":    str(LOGS_DIR / "db.log"),
            "maxBytes":    5 * 1024 * 1024,
            "backupCount": 10,
            "formatter":   "production",
            "level":       "DEBUG",
            "encoding":    "utf-8",
        },
 
        # security.log — auth, login, permission events
        "security_file": {
            "class":       "logging.handlers.RotatingFileHandler",
            "filename":    str(LOGS_DIR / "security.log"),
            "maxBytes":    5 * 1024 * 1024,
            "backupCount": 10,
            "formatter":   "production",
            "level":       "INFO",
            "encoding":    "utf-8",
        },
    },
 
    # ── Loggers ────────────────────────────────────────────────────────────────
    "loggers": {
 
        # ── Your 9 Django apps — each maps to app_name.views / app_name.* ─────
 
        "users": {
            "handlers":  ["console", "app_file", "error_file"],
            "level":     "DEBUG",
            "propagate": False,
        },
        "audit": {
            "handlers":  ["console", "app_file", "error_file"],
            "level":     "DEBUG",
            "propagate": False,
        },
        "dashboard": {
            "handlers":  ["console", "app_file", "error_file"],
            "level":     "DEBUG",
            "propagate": False,
        },
        "license": {
            "handlers":  ["console", "app_file", "error_file"],
            "level":     "DEBUG",
            "propagate": False,
        },
        "masters": {
            "handlers":  ["console", "app_file", "error_file"],
            "level":     "DEBUG",
            "propagate": False,
        },
        "maintenance": {
            "handlers":  ["console", "app_file", "error_file"],
            "level":     "DEBUG",
            "propagate": False,
        },
        "pettycash": {
            "handlers":  ["console", "app_file", "error_file"],
            "level":     "DEBUG",
            "propagate": False,
        },
        "projects": {
            "handlers":  ["console", "app_file", "error_file"],
            "level":     "DEBUG",
            "propagate": False,
        },
        "purchases": {
            "handlers":  ["console", "app_file", "error_file"],
            "level":     "DEBUG",
            "propagate": False,
        },
        "sales": {
            "handlers":  ["console", "app_file", "error_file"],
            "level":     "DEBUG",
            "propagate": False,
        },
        "reports": {
            "handlers":  ["console", "app_file", "error_file"],
            "level":     "DEBUG",
            "propagate": False,
        },
        "stock": {
            "handlers":  ["console", "app_file", "error_file"],
            "level":     "DEBUG",
            "propagate": False,
        },
 
        # ── Middleware-generated loggers ───────────────────────────────────────
        "app.request": {
            "handlers":  ["console", "app_file"],
            "level":     "INFO",
            "propagate": False,
        },
        "app.error": {
            "handlers":  ["console", "app_file", "error_file"],
            "level":     "ERROR",
            "propagate": False,
        },
        "app.security": {
            "handlers":  ["console", "app_file", "security_file"],
            "level":     "INFO",
            "propagate": False,
        },
 
        # ── DB signals logger ─────────────────────────────────────────────────
        "app.db": {
            "handlers":  ["console", "db_file"],
            "level":     "DEBUG",
            "propagate": False,
        },
 
        # ── Django internals (quiet in production) ────────────────────────────
        "django": {
            "handlers":  ["console", "error_file"],
            "level":     "WARNING",
            "propagate": False,
        },
        "django.request": {
            "handlers":  ["error_file"],
            "level":     "ERROR",
            "propagate": False,
        },
        "django.security": {
            "handlers":  ["security_file"],
            "level":     "WARNING",
            "propagate": False,
        },
        "django.db.backends": {
            # Uncomment the line below ONLY when debugging slow SQL queries
            # "level": "DEBUG",
            "handlers":  [],
            "level":     "WARNING",
            "propagate": False,
        },
    },
 
    # ── Root — catches any logger not matched above ────────────────────────────
    "root": {
        "handlers": ["console", "app_file", "error_file"],
        "level":    "WARNING",
    },
}
