# Generated by Django 6.0 on 2026-06-27 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_batch_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='restore_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_stock_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('add', 'Add Stock'), ('remove', 'Remove Stock'), ('damaged', 'Mark as Damaged'), ('expired', 'Mark as Expired')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='movement_type',
            field=models.CharField(choices=[('purchase_receipt', 'Purchase Receipt'), ('sale_dispatch', 'Sale Dispatch'), ('add', 'Manual Add'), ('remove', 'Manual Remove'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('restored', 'Restored'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('returned', 'Sales Return'), ('opening', 'Opening Balance')], max_length=25),
        ),
        migrations.CreateModel(
            name='StockAdjustmentBatchAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_allocations', to='stock.stockadjustment')),
                ('stock_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_allocations', to='stock.stockbatch')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
